### ISSUE TITLE
DeLijn doesn`t work anymore in release 2021.6

### ISSUE THREAD

**Issue by verhoevendanny** [bollewolle/delijn-card#9]
In stead of de passing info a text is displayed "no passages anymore today"

This is what i found in the errors.

File "/usr/src/homeassistant/homeassistant/components/delijn/sensor.py", line 74, in async_update
    await self.line.get_passages()
  File "/usr/local/lib/python3.8/site-packages/pydelijn/api.py", line 189, in get_passages
    linenumcolfronthex = colourshex.get(
AttributeError: 'NoneType' object has no attribute 'get'
2021-06-03 19:46:48 ERROR (MainThread) [homeassistant.components.sensor] delijn: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 432, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/components/delijn/sensor.py", line 74, in async_update
    await self.line.get_passages()
  File "/usr/local/lib/python3.8/site-packages/pydelijn/api.py", line 189, in get_passages
    linenumcolfronthex = colourshex.get(
AttributeError: 'NoneType' object has no attribute 'get'
2021-06-03 19:46:48 ERROR (MainThread) [homeassistant.components.sensor] delijn: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 432, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/components/delijn/sensor.py", line 74, in async_update
    await self.line.get_passages()
  File "/usr/local/lib/python3.8/site-packages/pydelijn/api.py", line 189, in get_passages
    linenumcolfronthex = colourshex.get(
AttributeError: 'NoneType' object has no attribute 'get'
2021-06-03 19:46:48 ERROR (MainThread) [homeassistant.components.sensor] delijn: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 432, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_device_update

**Comment by verhoevendanny** [comment]
After power down it worked again
